#!/bin/bash
set -euo pipefail

# Defaults
UNITY_LIBRARY_CACHE_DIR=${UNITY_LIBRARY_CACHE_DIR:-/tmp}
UNITY_PROJECT_PATH=${UNITY_PROJECT_PATH:-}
CACHE_FILE=${UNITY_LIBRARY_CACHE_DIR}/${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}.${BUILDKITE_JOB_ID}.tar.gz
CHECKOUT_PATH=$(cygpath -ua ${BUILDKITE_BUILD_CHECKOUT_PATH})
LIBRARY_PATH=${CHECKOUT_PATH}/${UNITY_PROJECT_PATH}/Library

echo "---Reloading Unity asset library"
echo "Library path: ${LIBRARY_PATH}"
echo "Cache path: ${CACHE_FILE}"

if [[ ! -f ${CACHE_FILE} ]]; then
  echo "No cache tarball found at ${CACHE_FILE}"
  echo "Skipping."
  exit 0
fi

set -x
tar -zxvf ${CACHE_FILE}
rm -f ${CACHE_FILE}