#!/bin/bash
set -euo pipefail

# Defaults
CACHE_DIR=${CACHE_DIR:-/tmp}
UNITY_PROJECT_PATH=${UNITY_PROJECT_PATH:-}
CACHE_FILE=${CACHE_DIR}/${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}.${BUILDKITE_JOB_ID}.tar.gz
LIBRARY_PATH=${BUILDKITE_BUILD_CHECKOUT_PATH}/${UNITY_PROJECT_PATH}/Library



echo "---Caching Unity asset library"
echo "Library path: ${LIBRARY_PATH}"
echo "Cache path: ${CACHE_FILE}"

set -x
tar -zcvf ${CACHE_FILE} ${LIBRARY_PATH}


